# https://www.navidrome.org/docs/usage/configuration-options/#available-options

# Basic Configuration
LogLevel = "INFO"
BaseURL = "/music"
ScanSchedule = "0"
DataFolder = "/var/vcap/store/navidrome"
MusicFolder = "/mnt/mcap/music"

# Advanced Configuration
FFmpegPath = "/opt/navidrome/ffmpeg/ffmpeg"
TranscodingCacheSize = "15MB"
EnableSharing = "true"
Prometheus.Enabled = "true"
