# Introduce the new repository
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/#repository-migration-november-8th-2022
- name: Install Grafana Apt Keys
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.asc


- name: Add Grafana Apt Repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/grafana.list
    content: |
      deb [signed-by=/usr/share/keyrings/grafana.asc] https://apt.grafana.com stable main


- name: Install grafana package
  ansible.builtin.apt:
    name: grafana=9.5.6
    state: present
    update_cache: true
  notify:
    - Systemd reload


- name: Install grafana configuration
  ansible.builtin.copy:
    src: root/etc/grafana/grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart grafana


- name: Ensure grafana is running
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
