- name: Setup NFS file sharing
  hosts: erebor

  tasks:
    - name: Create NFS read/write group
      become: true
      ansible.builtin.group:
        name: nfsrw
        state: present
        gid: 1980


    - name: Create NFS read/write user
      become: true
      ansible.builtin.user:
        name: nfsrw
        shell: /usr/sbin/nologin
        comment: "NFS read/write user"
        groups: nfsrw
        createhome: false
        uid: 1980


    - name: Create SMB read/write user
      become: true
      ansible.builtin.user:
        name: smbrw
        shell: /usr/sbin/nologin
        comment: "NFS read/write user"
        groups: nfsrw
        createhome: false
        uid: 1981


    - name: Ensure path is writeable by nfsrw group
      become: true
      ansible.builtin.file:
        path: /usr/local/var/mcap/store
        state: directory
        owner: root
        group: nfsrw
        mode: '0775'


    - name: Configure exports
      become: true
      ansible.builtin.copy:
        dest: /etc/exports
        owner: root
        group: wheel
        mode: '0644'
        content: |
          /usr/local/var/mcap/store -mapall=nfsrw:nfsrw \
          frodo.middle-earth.internal \
          merry.middle-earth.internal
      notify: restart nfs


    - name: Install packages
      become: true
      community.general.pkgng:
        pkg:
          - samba416


    # https://docs.freebsd.org/en/books/handbook/network-servers/index.html#network-samba
    - name: Configure samba
      become: true
      ansible.builtin.copy:
        dest: /usr/local/etc/smb4.conf
        owner: root
        group: wheel
        mode: '0644'
        content: |
          [global]
          workgroup = WORKGROUP
          server string = Samba Server Version %v
          netbios name = erebor
          wins support = No
          security = user
          passdb backend = tdbsam
          hostname lookups = yes

          [mcap]
          path = /usr/local/var/mcap/store
          writable  = yes
          browsable = yes
          guest ok = no
          create mask = 0664
          directory mask = 0775
          force group = nfsrw
          hosts allow = gandalf.middle-earth.internal
          hosts deny = ALL
      notify: restart samba


    - name: Load secrets from local file
      ansible.builtin.include_vars:
        file: ../secrets/smbrw_password.yml


    - name: Set samba password for smbrw using pdbedit
      become: true
      ansible.builtin.shell: |
        (echo "{{ smbrw_password }}"; echo "{{ smbrw_password }}") | pdbedit -a -t -u smbrw


    - name: Ensure nmbd is disabled
      become: true
      community.general.sysrc:
        name: nmbd_enable
        state: present
        value: "NO"


    - name: Ensure winbindd is disabled
      become: true
      community.general.sysrc:
        name: winbindd_enable
        state: present
        value: "NO"


    - name: Enable and start services
      become: true
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - nfsd
        - mountd
        - rpcbind
        - samba_server


  handlers:
    - name: restart nfs
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - rpcbind
        - mountd
        - nfsd


    - name: restart samba
      become: true
      service:
        name: samba_server
        state: restarted

# vim: ft=yaml.ansible
