- name: Create a user account for Nina
  hosts: pippin.middle-earth.internal.

  tasks:
    - name: Create Nina user
      become: true
      ansible.builtin.user:
        name: nina
        shell: /bin/bash
        comment: "Nina Boehm"
        home: /home/nina
        createhome: true


    - name: Add authorized keys
      become: true
      ansible.posix.authorized_key:
        user: nina
        state: present
        key: https://github.com/ninabohm.keys

# vim: ft=yaml.ansible
