- name: Update Authorized Keys
  hosts: pippin
  gather_facts: false

  tasks:
    - name: Refresh authorized keys for all relevant users
      become: true
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ lookup('file', '../../authorized_keys') }}"
      loop:
        - user: ansible

# vim: ft=yaml.ansible
