- name: Setup vhost directories
  ansible.builtin.file:
    path: /opt/{{ item.vhost }}
    state: directory
    owner: root
    group: admin
    mode: '0775'
  loop:
    - vhost: goodenoughmoney.com
    - vhost: home.scottmuc.com


- name: Install vhost configs
  ansible.builtin.copy:
    src: root/etc/nginx/sites-available/{{ item.vhost }}
    dest: /etc/nginx/sites-available/{{ item.vhost }}
    owner: root
    group: admin
    mode: '0664'
  notify:
    - Restart nginx
  loop:
    - vhost: goodenoughmoney.com
    - vhost: home.scottmuc.com


- name: Enable vhosts
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.vhost }}
    dest: /etc/nginx/sites-enabled/{{ item.vhost }}
    state: link
  loop:
    - vhost: goodenoughmoney.com
    - vhost: home.scottmuc.com

# vim: ft=yaml.ansible
