- name: Propagate my authorized keys to all hosts

  hosts: all
  gather_facts: false

  tasks:
    - name: Refresh authorized keys for specified users
      become: true
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '../authorized_keys') }}"
      loop: "{{ users_to_propogate_authorized_keys_to }}"

# vim: ft=yaml.ansible
